name: my_first_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_theme_switcher: ^2.0.8
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  material_symbols_icons: ^4.2711.0
  pinput: ^3.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_dark.png
